# Machine Learning Zoomcamp

## 1.8 Linear algebra refresher

Plan:

* Vector operations
* Multiplication
    * Vector-vector multiplication
    * Matrix-vector multiplication
    * Matrix-matrix multiplication
* Identity matrix
* Inverse

In [1]:
import numpy as np

## Vector operations

In [2]:
u = np.array([2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [3]:
# Scalar Multiplication
2 * u

array([ 4,  8, 10, 12])

In [4]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [5]:
# Vector Addition
u + v

array([3, 4, 5, 8])

In [6]:
# Vector Multiplication
u * v

array([ 2,  0,  0, 12])

## Multiplication

In [7]:
# shape is the size of the array and the first element of this tuple is 4. 
v.shape[0]

4

In [8]:
def vector_vector_multiplication(u, v):
    # Ensure these vectors have the same size by checking the 
    # shape of the vectors.
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [9]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [10]:
# numpy dot product function.
u.dot(v)

np.int64(14)

In [11]:
# Capital 'U' to denote matrix.
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [12]:
# shape is the size of the 2D array. 
U.shape

(3, 4)

In [13]:
# Print number of rows in the matrix.
U.shape[0]

3

In [14]:
# Print number of cols in the matrix.
U.shape[1]

4

In [15]:
def matrix_vector_multiplication(U, v):
    # Ensure the dimensionality match 
    # (num_of_col in U must match num_of_row in v).
    assert U.shape[1] == v.shape[0]

    # Define the dimensionality of the resulting vector.
    num_rows = U.shape[0]
    
    result_vec = np.zeros(num_rows)

    # Go through each row of the matrix U.
    for i in range(num_rows):
        result_vec[i] = vector_vector_multiplication(U[i], v)
    
    return result_vec

In [16]:
# The output is a 1-dimensional array (a 3x1 vector)
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [17]:
# numpy dot product function can perform matrix-vector multiplication with a 2D array
U.dot(v)

array([14,  5,  5])

In [18]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [19]:
def matrix_matrix_multiplication(U, V):
    # Ensure the dimensionality match so that 
    # the multiplications make sense
    assert U.shape[1] == V.shape[0]

    # The number of rows of the resulting matrix 
    # will come from the number of rows of matrix U.
    num_rows = U.shape[0]
    # The number of cols of the resulting matrix 
    # will come from the number of cols of matrix V.
    num_cols = V.shape[1]
    
    result_matrix = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result_matrix[:, i] = Uvi
    
    return result_matrix

In [20]:
# The output is a 2-dimensional array (a 3x3 matrix)
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [21]:
# numpy dot product function can perform matrix-matrix multiplication with a 2D array
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix
In an identity matrix, we have ones on the diagonal and zeros everywhere else.

When we take matrix U and multiplied by I (both have matching dimensionality), we get the matrix U back. E.g., `U . I = U` or  `I . U = U`. 

This is similar to `x * 1 = x` or `1 * x = x`. 

In [22]:
# By convention, we referred identity matrix with capital 'I'.
# I = np.eye(dimension)

I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [24]:
# V . I = V
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

Identity matrix is useful for explaining what a matrix inverse is.

Only square matrices have inverse. 

Square matrix is a matrix for which the number of rows is the same as the number of columns (e.g., 3 x 3 matrix, 4 x 4 matrix, 5 x 5 matrix, etc.).

In [25]:
# V[[row_idx_1, row_idx_2, ..., row_idx_n-1]] returns a matrix that includes all the row_idx. 
V[[0, 2]]

array([[1., 1., 2.],
       [0., 2., 1.]])

In [26]:
# Return a square matrix of size 3 x 3 that includes first three rows (row 0, row 1, and row 2) of matrix V. 
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [27]:
# Use np.linalg.inv(square_matrix) function to compute the inverse of a matrix.
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [28]:
# V^-1 . V = I, useful for linear regression.
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Further Readings
- [Machine Learning Zoomcamp 2023 notes from Peter Ernicke](https://knowmledge.com/2023/09/15/ml-zoomcamp-2023-introduction-to-machine-learning-part-9/)
- [Additional notes on Linear Algebra](https://github.com/MemoonaTahira/MLZoomcamp2022/blob/main/Notes/Week_1-intro_to_ML_linear_algebra/Notes_for_Chapter_1-Linear_Algebra.ipynb)

### Next 

Intro to Pandas